// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCluster(arg1:string):Promise<string>;

export function GetNamespacesFromCluster(arg1:string):Promise<Array<string>>;

export function ListClusters():Promise<Array<string>>;
