// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCluster(arg1) {
  return window['go']['main']['App']['AddCluster'](arg1);
}

export function GetNamespacesFromCluster(arg1) {
  return window['go']['main']['App']['GetNamespacesFromCluster'](arg1);
}

export function GetResourcesFromNamespace(arg1, arg2) {
  return window['go']['main']['App']['GetResourcesFromNamespace'](arg1, arg2);
}

export function GetWorkloadsFromNamespace(arg1, arg2) {
  return window['go']['main']['App']['GetWorkloadsFromNamespace'](arg1, arg2);
}

export function ListClusters() {
  return window['go']['main']['App']['ListClusters']();
}
